#!/usr/bin/env python
# 
#  Copyright 2014 Glossom, inc. All rights reserved.
#
import sys
sys.dont_write_bytecode = True
import os
import json
from Pbxproj import Pbxproj

#load config file
__location__ = os.path.dirname(os.path.realpath(__file__))
f = open(os.path.join(__location__, 'config.json'))
data = json.load(f)

if(data['frameworks']):
	frameworks = data['frameworks']

print "--------------PostprocessBuildPlayer_GreeAdsReward start---------------------"
argvs = sys.argv
path = argvs[1] + "/Unity-iPhone.xcodeproj"

print "Modify iphone project file: ", path

project = Pbxproj.get_pbxproj_by_name(path, xcode_version = None)

if project:
  for framework in frameworks.iterkeys():
    print "add framework %s as %s" % (framework, "optional" if frameworks[framework] else "required") 
    project.add_framework(framework, frameworks[framework])
else:
  print "can not find iphone project"

print "--------------PostprocessBuildPlayer_GreeAdsReward end---------------------"
